# ??? ??????????
spring.application.name=school

# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog

# ?????????????? ?????????? ????? ??  (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

# ????????? ????? ??? ???????? ????????
path.to.avatars.folder=/avatars

# ???? ???????? ???? ?????? Liquibase
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

# ???? ??????????
server.port=8080


# ???????????
logging.level.root=INFO

# ?????? ???????????
logging.level.ru.hogwarts.school.service.AvatarService=DEBUG
logging.level.ru.hogwarts.school.service.FacultyService=DEBUG
logging.level.ru.hogwarts.school.service.StudentService=DEBUG

logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN

! ??????? ?????? ?????
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/hogwarts.log
logging.file.max-size=10MB
logging.file.max-history=20



